### ISSUE TITLE
Need ScopeObserver

### ISSUE THREAD

**Issue by thegreystone** [opentracing-contrib/java-api-extensions#18]
For this to be truly useful, I would need to also be able to observe the thread local span activations (scopes). Could this perhaps be an enhancement? The code for my jfr-tracer could then be greatly simplified.

https://github.com/thegreystone/jfr-tracer

**Comment by objectiser** [comment]
@thegreystone Sounds like a reasonable request - would you be interested in contributing a PR?

**Comment by thegreystone** [comment]
I would be interested in contributing the entire jfr-tracer project, but I think it would be better if someone else with more familiarity with the java-api-extensions did this part.

**Comment by thegreystone** [comment]
Does these extensions work with all of the tracers from all of the providers, or do the tracers need to do some work? I am asking, since not all tracers have the concept of TraceID, SpanID etc. (For example, Oracle OMC APM does not.)

**Comment by objectiser** [comment]
Not sure - one issue is that the tracer impls need to use the standard API of any supplied type (e.g. Span) - sometimes they expect the provided object to be their own impl.

A possible workaround was suggested [here](https://github.com/opentracing-contrib/java-api-extensions/issues/16#issuecomment-400636434), but just a case of finding someone to try it out.

**Comment by thegreystone** [comment]
I think most tracers expect to be able to downcast to their own implementations. Will have to take a look at your implementation a bit more closely.

**Comment by thegreystone** [comment]
Fixed.
