### ISSUE TITLE
Release 0.5.0 not available in maven central

### ISSUE THREAD

**Issue by fatroom** [opentracing-contrib/java-api-extensions#22]
From the releases page here and tags I see that release 0.5.0 was created, but this release was not published to maven central, so it's not available to users. Can you publish it?

**Comment by sjoerdtalsma** [comment]
Master build failed: https://travis-ci.org/opentracing-contrib/java-api-extensions/builds/574447365
```log
[ERROR] Failed to execute goal io.zipkin.centralsync-maven-plugin:centralsync-maven-plugin:0.1.0:sync (default-cli) on project opentracing-api-extensions-parent: https://api.bintray.com/maven_central_sync/opentracing/maven/opentracing-api-extensions/versions/0.5.0 failed: Response{protocol=http/1.1, code=400, message=Bad Request, url=https://api.bintray.com/maven_central_sync/opentracing/maven/opentracing-api-extensions/versions/0.5.0} -> [Help 1]
```

**Comment by sjoerdtalsma** [comment]
The upload to bintray seems to still work:
```log
[INFO] Uploaded: https://api.bintray.com/maven/opentracing/maven/opentracing-api-extensions/;publish=1/io/opentracing/contrib/opentracing-api-extensions/0.5.0/opentracing-api-extensions-0.5.0.jar (4.1 kB at 842 B/s)
[INFO] Uploaded: https://api.bintray.com/maven/opentracing/maven/opentracing-api-extensions/;publish=1/io/opentracing/contrib/opentracing-api-extensions/0.5.0/opentracing-api-extensions-0.5.0-sources.jar (7.0 kB at 1.5 kB/s)
[INFO] Uploaded: https://api.bintray.com/maven/opentracing/maven/opentracing-api-extensions/;publish=1/io/opentracing/contrib/opentracing-api-extensions/0.5.0/opentracing-api-extensions-0.5.0-javadoc.jar (41 kB at 8.8 kB/s)
```

**Comment by sjoerdtalsma** [comment]
@adriancole Do you have any idea how/why the `io.zipkin.centralsync-maven-plugin:centralsync-maven-plugin:0.1.0` seems to send a _Bad request_ to maven-central for this repository?

**Comment by codefromthecrypt** [comment]
we bumped versions slightly just to up dependency versions. you can see if
0.1.1 gives any better or different output. otherwise, you can send the
response to support@bintray.com who might be able to answer. good luck

**Comment by objectiser** [comment]
I've manually triggered the sync from bintray so should hopefully be available in maven central soon.

**Comment by sjoerdtalsma** [comment]
> I've manually triggered the sync from bintray so should hopefully be available in maven central soon.

Although this technically resolves this issue, we shouldn't depend on this manual process for releases i.m.o.

**Comment by objectiser** [comment]
Agree.

@fatroom artifacts are now available in maven central.
