### ISSUE TITLE
Create a Tracer wrapper that provides support for the APIs

### ISSUE THREAD

**Issue by objectiser** [opentracing-contrib/java-api-extensions#5]
Although some `Tracer` implementations may wish to natively support the observer and filter APIs, it would be useful to provide a `Tracer` wrapper that handles the management of these APIs in a tracer provider independent way. As discussed here: https://github.com/opentracing-contrib/java-observer/pull/3#issuecomment-312255658

**Comment by sjoerdtalsma** [comment]
I think it might be useful to explicitly define (and document) the extension API methods in an `interface` rather than merely defining a wrapper impl.

That way API extension-support by  native tracers can avoid wrapping altogether merely by checking for 'instanceof ' the _interface_.
