### ISSUE TITLE
Rename repository to reflect wider scope than just observer API

### ISSUE THREAD

**Issue by objectiser** [opentracing-contrib/java-api-extensions#6]
As discussed in this thread (https://github.com/opentracing-contrib/java-observer/pull/3#issuecomment-312227092) we should rename this repo to something more appropriate to cover observer and filter API.

`java-patterns` - too generic
`java-tracer-decorator` and `java-tracer-wrapper` - I think these are too implementation specific, and focus just on the wrapping/decorator rather than on the APIs
`java-api-extensions` and `java-tracer-extensions` - these are in the right direction, wonder if a truncated form would work - e.g. `java-ext`

**Comment by pavolloffay** [comment]
The most I like is 
`java-api-extensions`. `java-ext` is not story telling at the first glance I don't know what is there.

**Comment by yurishkuro** [comment]
why not simply use different repos?

**Comment by objectiser** [comment]
@yurishkuro Was thinking that the filter/interceptor API would also use the `SpanData` to enable more interesting possibilities.

**Comment by yurishkuro** [comment]
It's it worth creating intermodule dependencies because of one pojo?

**Comment by objectiser** [comment]
The APIs should be in a single module, but the wrapper discussed in https://github.com/opentracing-contrib/java-observer/issues/5 would probably be better in a separate module.

**Comment by objectiser** [comment]
@pavolloffay @felixbarny @yurishkuro As part of this issue, would like to do the following:

- [ ] Rename the repo to `java-api-extensions` (as proposed by Pavol)
- [ ] Artifact id changed to `opentracing-api-extensions`
- [ ] Place interfaces into package `io.opentracing.contrib.api`

Any objections?
